# Test Makefile for ubus linking verification
# Run inside OpenWrt SDK Docker container

TARGET_DIR = /opt/target
CC = aarch64-openwrt-linux-musl-gcc
CFLAGS = -I$(TARGET_DIR)/usr/include -O2 -Wall
LDFLAGS = -L$(TARGET_DIR)/usr/lib -lubus -lubox -lblobmsg_json -ljson-c

test_ubus: test_ubus.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)
	file $@

clean:
	rm -f test_ubus
