/*
 * Services page control hooks (ADR0006)
 */
#ifndef PAGE_SERVICES_H
#define PAGE_SERVICES_H

#include <stdbool.h>
#include <stdint.h>

/*
 * Consume a pending control request generated by the Services page.
 * Returns true if a request was available and clears the pending flag.
 */
bool page_services_take_control_request(int *index, bool *start, uint64_t now_ms);

/*
 * Notify the Services page about control result (for UI feedback).
 */
void page_services_notify_control_result(int index, bool success);

#endif
